In [6]:
import numpy as np
import time

In [7]:
x = np.random.random(200)

In [8]:
start = time.time()
sum(x) / len(x)
print(time.time() - start)

0.0


In [9]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.0


In [10]:
# Creating numpy from regular python list
x = np.array([1, 2, 3, 4, 34, 3, 4])
print(x)
print(type(x))

[ 1  2  3  4 34  3  4]
<class 'numpy.ndarray'>


In [11]:
x.dtype

dtype('int32')

In [12]:
x.shape

(7,)

In [14]:
y = np.array([[1, 2, 3, 2, 23], [23, 2, 2, 2, 2]])

In [15]:
y

array([[ 1,  2,  3,  2, 23],
       [23,  2,  2,  2,  2]])

In [16]:
y.shape

(2, 5)

In [17]:
x = np.array([2, 2, 4, 3.4, 2.3]) # Upcasting of the arrays..

In [19]:
x.dtype

dtype('float64')

In [20]:
x.ndim

1

In [21]:
y = np.zeros((2, 3, 4))

In [22]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
y.ndim

3

In [24]:
y.shape

(2, 3, 4)

In [28]:
# Specifying an array of integers
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

In [29]:
x

array([1, 2, 3, 4, 5], dtype=int64)

In [30]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [31]:
Y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
Y.shape, Y.size, type(Y), Y.dtype

((4, 3), 12, numpy.ndarray, dtype('int32'))

In [34]:
np.save('my_y_array', Y)

In [36]:
z = np.load("my_y_array.npy")

In [37]:
z.shape

(4, 3)

In [40]:
letter_array = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

In [41]:
letter_array.dtype

dtype('<U1')

In [42]:
letter_array.shape

(10,)

In [43]:
letter_array.size

10

In [45]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
z = np.ones((1, 3))

In [48]:
z

array([[1., 1., 1.]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [53]:
np.diag([2, 3, 4, 4])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]])

In [54]:
x = np.arange(10)

In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
z = np.arange(1, 11)

In [57]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
x = np.linspace(1, 100, 20)

In [63]:
x

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [64]:
x = np.array([1, 2, 3])

ValueError: cannot reshape array of size 3 into shape (1,)

In [70]:
z = np.random.randint(1, 100, (1, 2))

In [71]:
z

array([[62, 73]])

In [74]:
#  np.zeros()
#  np.ones()
#  np.zeros()
#  np.full(array_shape, constant_value)
#  np.eye(5) - Creates an identity array = a square of 5 by 5 with 1's as diagonals
#  np.diag([1,2,3,4]) - Create a diagonal square matrix with the similar scripts
#  np.arange() - Functions similar to range() function but specific to numpy with both steps an data type
#  dtype

In [76]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)
# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [95]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [86]:
np.linspace(1, 5, 11, endpoint=True)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [89]:
x = np.arange(20)

# We print x
print()
print('Original x = ', x)
print()

# We reshape x into a 4 x 5 ndarray
x = np.reshape(x, (4,5))

# We print the reshaped x
print()
print('Reshaped x = \n', x)
print()

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [90]:
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

In [91]:
X

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [92]:
X = np.random.random((3, 3))

In [93]:
X

array([[0.29806216, 0.11210417, 0.04234255],
       [0.00618263, 0.50320915, 0.75036273],
       [0.01757168, 0.37911506, 0.49571461]])

In [94]:
# np.random.randint(start, stop, shape)

In [96]:
# np.random.normal(mean, sd, size=shape)

In [97]:
y = np.array([2, 3, 2, 3])

In [100]:
np.append(Y, [2,23,2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  2, 23,  2])

In [101]:
# np.vstack((x,y))
# np.hstack((x,y))

In [104]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0])
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])


x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


In [110]:
x = np.delete(x, 0, axis=0)

In [111]:
x

array([2, 3, 4, 5])

In [114]:
x = np.append(x, [32, 2, 3, 2], axis=0)

In [115]:
x

array([ 2,  3,  4,  5, 32,  2,  3,  2])

In [118]:
np.insert(x, 5, 2, 0)

array([ 2,  3,  4,  5, 32,  2,  2,  3,  2])

In [119]:
# numpy.hstack(sequence_of_ndarray)
# numpy.vstack(sequence_of_ndarray)

In [121]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [122]:
y = np.arange(20).reshape(4, 5)

In [123]:
Z = np.copy(Y[1:4, 2:5])

In [124]:
Z

array([[ 6],
       [ 9],
       [12]])

In [125]:
# Slicing an array to another variable only creates a view of the previous array - need to use copy to get a different array

In [134]:
z = np.eye(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [137]:
value_to_diagonal = np.diag(z, k=-4)

In [138]:
value_to_diagonal

array([0.])

In [144]:
y = np.array([2, 3, 4, 2, 2, 2, 23, 5, 45, 45, 67])

In [146]:
y_unique = np.unique(y)

In [147]:
y_unique

array([ 2,  3,  4,  5, 23, 45, 67])

In [148]:
# Erratum

In [149]:
# Boolean Indexing
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



In [153]:
x = [1, 2, 3, 4, 5, 6, 7]
y = [5, 6, 7, 8, 9, 10]
z = [8, 9, 10, 11]

print("Intersection of {} and {} is {}".format(x, y, np.intersect1d(x, y)))
print("The Union of {} and {} is {}".format(x, z, np.union1d(x, z)))
print("The Set Difference of {} and {} is {}".format(x, y, np.setdiff1d(x, y)))

Intersection of [1, 2, 3, 4, 5, 6, 7] and [5, 6, 7, 8, 9, 10] is [5 6 7]
The Union of [1, 2, 3, 4, 5, 6, 7] and [8, 9, 10, 11] is [ 1  2  3  4  5  6  7  8  9 10 11]
The Set Difference of [1, 2, 3, 4, 5, 6, 7] and [5, 6, 7, 8, 9, 10] is [1 2 3 4]


In [154]:
z = np.array([7, 6, 5, 4, 3, 2, 1])

In [155]:
z

array([7, 6, 5, 4, 3, 2, 1])

In [158]:
z.sort()

In [159]:
z

array([1, 2, 3, 4, 5, 6, 7])

In [160]:
# Arithmetic Operation on Array
# np.add()
# np.multiply()
# np.subtract()

In [161]:
X = np.ones((4,4)) * np.arange(1,5)

In [162]:
X

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])